package vcmsa.lwandle.mealprepperfectprep

import android.os.Bundle
import android.widget.EditText
import android.widget.ImageView
import android.widget.TextView
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class Breakfast : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Enable edge-to-edge feature for modern devices
        enableEdgeToEdge()

        // Set the content view to the activity layout
        setContentView(R.layout.activity_breakfast)

        // Adjust padding for system bars (like status bar and navigation bar)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

        // Initialize UI elements
        val headerText = findViewById<EditText>(R.id.editTextText4)
        val pancakesImage = findViewById<ImageView>(R.id.imageView8)
        val parfaitImage = findViewById<ImageView>(R.id.imageView9)
        val bowlImage = findViewById<ImageView>(R.id.imageView10)

        val pancakesText = findViewById<TextView>(R.id.textView6)
        val parfaitText = findViewById<TextView>(R.id.textView7)
        val bowlText = findViewById<TextView>(R.id.textView8)

        // Click listeners for images
        pancakesImage.setOnClickListener {
            showToast("Fluffy Pancakes: The perfect start to your day!")
        }

        parfaitImage.setOnClickListener {
            showToast("Yoghurt Parfait: A light and nutritious choice!")
        }

        bowlImage.setOnClickListener {
            showToast("Savory Breakfast Bowl: A balanced and tasty meal!")
        }

        // Click listeners for text labels
        pancakesText.setOnClickListener {
            headerText.setText("Fluffy Pancakes Recipe")
        }

        parfaitText.setOnClickListener {
            headerText.setText("Yoghurt Parfait Recipe")
        }

        bowlText.setOnClickListener {
            headerText.setText("Savory Breakfast Bowl Recipe")
        }
    }
          //this code has been generated by ai
    // Show toast message
    private fun showToast(message: String) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
    }
}
