package vcmsa.lwandle.mealprepperfectprep

import android.os.Bundle
import android.widget.EditText
import android.widget.ImageView
import android.widget.TextView
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class Dinner : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_dinner)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }
        // Initialize UI elements
        val headerText = findViewById<EditText>(R.id.editTextText6)
        val salmonImage = findViewById<ImageView>(R.id.imageView17)
        val tofuImage = findViewById<ImageView>(R.id.imageView18)
        val noodlesImage = findViewById<ImageView>(R.id.imageView21)

        val salmonText = findViewById<TextView>(R.id.textView13)
        val tofuText = findViewById<TextView>(R.id.textView14)
        val noodlesText = findViewById<TextView>(R.id.textView15)

        // Click listeners for images
        salmonImage.setOnClickListener {
            showToast("Grilled Salmon: A delicious and healthy choice!")
        }

        tofuImage.setOnClickListener {
            showToast("Veggie Tofu Stir-fry: A perfect vegetarian option!")
        }

        noodlesImage.setOnClickListener {
            showToast("Zucchini Pesto Noodles: A fresh and light meal!")
        }

        // Click listeners for text labels
        salmonText.setOnClickListener {
            headerText.setText("Grilled Salmon Recipe")
        }

        tofuText.setOnClickListener {
            headerText.setText("Veggie Tofu Stir-fry Recipe")
        }

        noodlesText.setOnClickListener {
            headerText.setText("Zucchini Pesto Noodles Recipe")
        }
    }
     //This was generated by ChatGPT
    private fun showToast(message: String) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
    }
}
