package vcmsa.lwandle.mealprepperfectprep

import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.ImageView
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity

class TimeSlotActivity : AppCompatActivity() {

    private lateinit var mealSelectionText: EditText
    private var selectedMeal: String? = null  // Stores the user's selected meal

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_time_slot)

        // Initialize UI elements
        mealSelectionText = findViewById(R.id.editTextText)

        val breakfastImage: ImageView = findViewById(R.id.imageView5)
        val lunchImage: ImageView = findViewById(R.id.imageView6)
        val dinnerImage: ImageView = findViewById(R.id.imageView7)
        val snackImage: ImageView = findViewById(R.id.imageView24)

        val selectButton: Button = findViewById(R.id.button)

        // Set click listeners for meal selection
        breakfastImage.setOnClickListener { updateSelectedMeal("Breakfast") }
        lunchImage.setOnClickListener { updateSelectedMeal("Lunch") }
        dinnerImage.setOnClickListener { updateSelectedMeal("Dinner") }
        snackImage.setOnClickListener { updateSelectedMeal("Afternoon Snack") }

        // Handle "Select" button click
        selectButton.setOnClickListener {
            selectedMeal?.let {
                Toast.makeText(this, "You selected: $it", Toast.LENGTH_SHORT).show()
            } ?: run {
                Toast.makeText(this, "Please select a meal", Toast.LENGTH_SHORT).show()
            }
        }
    }


    // This was generated by chatgpt.
    private fun updateSelectedMeal(meal: String) {
        selectedMeal = meal
        mealSelectionText.setText(meal) // Update the text field
    }
}
